export PYTHONPATH=~/Code/Pythonlibs:$PYTHONPATH
export GOPATH=~/Code/Go/
export PATH=~/bin/:$GOPATH/bin:~/.cabal/bin:~/Library/Miniconda3/bin:~/.cargo/bin:$PATH
export EDITOR=vim
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export MOSEKLM_LICENSE_FILE=$HOME/Library/mosek/mosek.lic
export RUST_SRC_PATH=/usr/local/src/rust/src
PATH=$PATH:$HOME/.local/bin
