#!/bin/bash

xmodmap ~/.Xmodmap
xinput disable "SynPS/2 Synaptics TouchPad"

XCAPSEXEC=~/.dotfiles/xcape/xcape
if [[ -a $XCAPSEXEC ]]; then
   setxkbmap -option ctrl:nocaps
   eval "$XCAPSEXEC" -e 'Control_L=Escape' -t 250
else
   setxkbmap -option caps:swapescape
fi

xmodmap ~/.Xmodmap

xsetwacom --set "Wacom ISDv4 90 Pen stylus" Button 1 "button +1"
xsetwacom --set "Wacom ISDv4 90 Pen stylus" Button 2 "button +3"
xsetwacom --set "Wacom ISDv4 90 Pen eraser" Button 1 "button +2"
xsetwacom --set "Wacom ISDv4 90 Pen stylus" Area 132 -14 27608 15462
xsetwacom --set "Wacom ISDv4 90 Pen eraser" Area 132 -14 27608 15462
